### ISSUE TITLE
Getting read timed out while running query on a large table

### ISSUE THREAD

**Issue by BogdanCojocar** [springml/spark-salesforce#13]
Hey guys,

This library is great, and it's really making things easier. Thanks for developing this. Unfortunately I encountered a problem while querying a large table:

```
    val spark = SparkSession
      .builder
      .master("local[*]")
      .appName("Spark test salesforce")
      .getOrCreate()

    val df = spark
      .read
      .format("com.springml.spark.salesforce")
      .option("username", "")
      .option("password", "")
      .option("soql", "")
      .option("inferSchema", "true")
      .load()
```

But i get:

```
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.springml.salesforce.wave.util.HTTPHelper.execute(HTTPHelper.java:95)
	at com.springml.salesforce.wave.util.HTTPHelper.get(HTTPHelper.java:75)
	at com.springml.salesforce.wave.util.HTTPHelper.get(HTTPHelper.java:79)
	at com.springml.salesforce.wave.impl.ForceAPIImpl.query(ForceAPIImpl.java:120)
	at com.springml.salesforce.wave.impl.ForceAPIImpl.query(ForceAPIImpl.java:36)
	at com.springml.spark.salesforce.DatasetRelation.querySF(DatasetRelation.scala:117)
	at com.springml.spark.salesforce.DatasetRelation.read(DatasetRelation.scala:59)
	at com.springml.spark.salesforce.DatasetRelation.<init>(DatasetRelation.scala:51)
	at com.springml.spark.salesforce.DefaultSource.createRelation(DefaultSource.scala:92)
	at com.springml.spark.salesforce.DefaultSource.createRelation(DefaultSource.scala:54)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:315)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:122)
	at TestSalesforceConnector$.main(TestSalesforceConnector.scala:34)
	at TestSalesforceConnector.main(TestSalesforceConnector.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Exception in thread "main" java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.springml.salesforce.wave.util.HTTPHelper.execute(HTTPHelper.java:95)
	at com.springml.salesforce.wave.util.HTTPHelper.get(HTTPHelper.java:75)
	at com.springml.salesforce.wave.util.HTTPHelper.get(HTTPHelper.java:79)
	at com.springml.salesforce.wave.impl.ForceAPIImpl.query(ForceAPIImpl.java:120)
	at com.springml.salesforce.wave.impl.ForceAPIImpl.query(ForceAPIImpl.java:36)
	at com.springml.spark.salesforce.DatasetRelation.querySF(DatasetRelation.scala:117)
	at com.springml.spark.salesforce.DatasetRelation.read(DatasetRelation.scala:59)
	at com.springml.spark.salesforce.DatasetRelation.<init>(DatasetRelation.scala:51)
	at com.springml.spark.salesforce.DefaultSource.createRelation(DefaultSource.scala:92)
	at com.springml.spark.salesforce.DefaultSource.createRelation(DefaultSource.scala:54)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:315)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:122)
	at TestSalesforceConnector$.main(TestSalesforceConnector.scala:34)
	at TestSalesforceConnector.main(TestSalesforceConnector.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

Testing on my local machine:

```
Java Home	/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre
Java Version	1.8.0_112 (Oracle Corporation)
Scala Version	version 2.11.8
```
 Is there a parameter to increase the read time for large tables?

Appreciate the help.

Thanks,
Bogdan

**Comment by BogdanCojocar** [comment]
As a side not, if I use a limit on my query I am able to get the data.

**Comment by BogdanCojocar** [comment]
I guess the problem might be coming from here:

```
private def querySF(): java.util.List[java.util.Map[String, String]] = {
      var records: java.util.List[java.util.Map[String, String]]= null;

      var resultSet = forceAPI.query(query)
      records = resultSet.filterRecords()

      while (!resultSet.isDone()) {
        resultSet = forceAPI.queryMore(resultSet)
        records.addAll(resultSet.filterRecords())
      }

      return records
  }
```
Does this api supports bulk queries for soql?

**Comment by springml** [comment]
@BogdanCojocar  @jjamesstark We don't use Bulk job for querying. But we are using queryMore and hence read time out should not occur. 

Could you please try decreasing the no.of records fetched in a single call using pageSize option. Default value for pageSize is 1000. Probably you can try with 500. 

Also please using the latest connector as we fixed some minor issues.

**Comment by springml** [comment]
@BogdanCojocar @jjamesstark I am closing the ticket for now. If you see this issue again, please create a new ticket or reopen this ticket
