### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/http/client/config/RequestConfig

### ISSUE THREAD

**Issue by progressstack** [springml/spark-salesforce#19]
Hi , 

I am getting this below error when trying to extract data from salesforce using SOQL method, this is happening in CDH 5.9.2 in spark 1.6

java.lang.NoClassDefFoundError: org/apache/http/client/config/RequestConfig
        at com.springml.salesforce.wave.util.HTTPHelper.getRequestConfig(HTTPHelper.java:129)
        at com.springml.salesforce.wave.util.HTTPHelper.get(HTTPHelper.java:63)
        at com.springml.salesforce.wave.util.HTTPHelper.get(HTTPHelper.java:79)
        at com.springml.salesforce.wave.impl.ForceAPIImpl.query(ForceAPIImpl.java:120)
        at com.springml.salesforce.wave.impl.ForceAPIImpl.query(ForceAPIImpl.java:36)
        at com.springml.spark.salesforce.DatasetRelation.querySF(DatasetRelation.scala:119)
        at com.springml.spark.salesforce.DatasetRelation.read(DatasetRelation.scala:61)
        at com.springml.spark.salesforce.DatasetRelation.<init>(DatasetRelation.scala:53)
        at com.springml.spark.salesforce.DefaultSource.createRelation(DefaultSource.scala:96)
        at com.springml.spark.salesforce.DefaultSource.createRelation(DefaultSource.scala:54)
        at com.springml.spark.salesforce.DefaultSource.createRelation(DefaultSource.scala:40)
        at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:158)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:34)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:39)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:41)
        at $iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:43)

**Comment by samuel-pt** [comment]
Please provide more information about your environment like what hadoop distribution you are using, are you using zeppelin and so on

**Comment by kali786516** [comment]
Cloudera 5.9 enterprise
