### ISSUE TITLE
Running into org.apache.spark.sql.execution.datasources.csv.CSVFileFormat

### ISSUE THREAD

**Issue by jayantshekhar** [springml/spark-salesforce#21]
I'm using the below dependency and running into an exception. Its probably because maven central has not been updated since March 2017 : https://mvnrepository.com/artifact/com.springml/spark-salesforce

        <dependency>
            <groupId>com.springml</groupId>
            <artifactId>spark-salesforce_2.11</artifactId>
            <version>1.1.0</version>
        </dependency>

## Exception

java.lang.RuntimeException: Multiple sources found for csv (org.apache.spark.sql.execution.datasources.csv.CSVFileFormat, com.databricks.spark.csv.DefaultSource15), please specify the fully qualified class name.
	at scala.sys.package$.error(package.scala:27)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:616)
	at org.apache.spark.sql.execution.datasources.DataSource.providingClass$lzycompute(DataSource.scala:86)
	at org.apache.spark.sql.execution.datasources.DataSource.providingClass(DataSource.scala:86)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:325)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:152)

**Comment by samuel-pt** [comment]
@jayantshekhar Could you please update the code snippet which results in the above error?

**Comment by msathiyarajan** [comment]
@jayantshekhar have you added the com.databricks:spark-csv_2.11:1.4.0 dependency in your project?
I don't think this problem arises due to springml dependency.

**Comment by federicomartinlara1976** [comment]
> @jayantshekhar have you added the com.databricks:spark-csv_2.11:1.4.0 dependency in your project?
> I don't think this problem arises due to springml dependency.
> 
> use the maven dependency https://mvnrepository.com/artifact/com.databricks/spark-csv_2.11/1.4.0 and save it with the following run sfDF.write.format("com.databricks.spark.csv").option("header", "false").save("output.csv")

This solution don't work. It's NOT have tested. You lies.
