### ISSUE TITLE
SOQL URL Encode not working for comparison operators

### ISSUE THREAD

**Issue by schwartzmx** [springml/spark-salesforce#3]
First off, thanks for these awesome tools.   It has been really easy to work with!

The problem I am running into is trying to do incremental pulls from SF using SOQL and the `LastModifiedDate` field.   I'm grabbing the max date from our DW db and trying to use that as a filter in the SOQL query,  however it seems using comparison operator like `>=` is not being URL encoded properly for the API request, specifically `=`.

Below is the query and stack trace.

``` sql
      select 
        ID
        ,Name
      from Account  
      where LastModifiedDate >= 2016-09-13T15:31:37.000+0000
```

``` sh
16/09/20 11:15:49 WARN ForceAPIImpl: Error while executing salesforce query 
java.lang.Exception: Accessing https://XXXX.my.salesforce.com/services/data/v37.0/query?q=%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20select%20%0A%20%20%20%20%20%20%20%20ID%0A%20%20%20%20%20%20%20%20,Name%0A%0A%20%20%20%20%20%20from%20Account%20%20where%20LastModifiedDate%20%3E=%202016-09-13T15:31:37.000+0000%0A%20%20%20%20 failed. Status 400. Reason Bad Request 
 Error from server [{"message":"line 5:69 no viable alternative at character ' '","errorCode":"MALFORMED_QUERY"}]
    at com.springml.salesforce.wave.util.HTTPHelper.execute(HTTPHelper.java:102)
    at com.springml.salesforce.wave.util.HTTPHelper.get(HTTPHelper.java:75)
    at com.springml.salesforce.wave.util.HTTPHelper.get(HTTPHelper.java:79)
    at com.springml.salesforce.wave.impl.ForceAPIImpl.query(ForceAPIImpl.java:47)
    at com.springml.salesforce.wave.impl.ForceAPIImpl.query(ForceAPIImpl.java:32)
    at com.springml.spark.salesforce.DatasetRelation.querySF(DatasetRelation.scala:84)
    at com.springml.spark.salesforce.DatasetRelation.read(DatasetRelation.scala:56)
    at com.springml.spark.salesforce.DatasetRelation.<init>(DatasetRelation.scala:48)
    at com.springml.spark.salesforce.DefaultSource.createRelation(DefaultSource.scala:84)
    at com.springml.spark.salesforce.DefaultSource.createRelation(DefaultSource.scala:53)
    at com.springml.spark.salesforce.DefaultSource.createRelation(DefaultSource.scala:39)
    at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:158)
    at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)
    at org.lucidhq.SFRedshiftETL.Table.sfRead(Table.scala:95)
    at org.lucidhq.SFRedshiftETL.Table.load(Table.scala:166)
    at org.lucidhq.SFRedshiftETL.SFRedshiftETL$$anonfun$run$1.apply(main.scala:55)
    at org.lucidhq.SFRedshiftETL.SFRedshiftETL$$anonfun$run$1.apply(main.scala:43)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at org.lucidhq.SFRedshiftETL.SFRedshiftETL$.run(main.scala:43)
    at org.lucidhq.SFRedshiftETL.SFRedshiftETL$$anonfun$main$1.apply(main.scala:60)
    at org.lucidhq.SFRedshiftETL.SFRedshiftETL$$anonfun$main$1.apply(main.scala:60)
    at scala.Option.map(Option.scala:145)
    at org.lucidhq.SFRedshiftETL.SFRedshiftETL$.main(main.scala:60)
    at org.lucidhq.SFRedshiftETL.SFRedshiftETL.main(main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
    at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)
    at org.lucidhq.SFRedshiftETL.Table.sfRead(Table.scala:95)
    at org.lucidhq.SFRedshiftETL.Table.load(Table.scala:166)
    at org.lucidhq.SFRedshiftETL.SFRedshiftETL$$anonfun$run$1.apply(main.scala:55)
    at org.lucidhq.SFRedshiftETL.SFRedshiftETL$$anonfun$run$1.apply(main.scala:43)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at org.lucidhq.SFRedshiftETL.SFRedshiftETL$.run(main.scala:43)
    at org.lucidhq.SFRedshiftETL.SFRedshiftETL$$anonfun$main$1.apply(main.scala:60)
    at org.lucidhq.SFRedshiftETL.SFRedshiftETL$$anonfun$main$1.apply(main.scala:60)
    at scala.Option.map(Option.scala:145)
    at org.lucidhq.SFRedshiftETL.SFRedshiftETL$.main(main.scala:60)
    at org.lucidhq.SFRedshiftETL.SFRedshiftETL.main(main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

Using chrome dev tools from the SF Apex Query Console, I was able to to find the correct URL for the same query.

```
https://XXXX.my.salesforce.com/services/data/v38.0/query/?q=select%20%0A%20%20%20%20%20%20%20%20ID%0A%20%20%20%20%20%20%20%20%2CName%0A%20%20%20%20%20%20from%20Account%20%20where%20LastModifiedDate%20%3E%3D%202016-09-13T15%3A31%3A37.000%2B0000&columns=true&_=1474388317509
```

This seems to be a problem with the wave API wrapper's URL-encoding specifically with that `=` sign,  if the issue should be raised in that repo, please close this.   

I just experienced the problem with this connector so I figured I'd raise the issue here.

Thanks

**Comment by samuel-pt** [comment]
Thanks for raising this issue. We found that this issue is with the "." and "+" in the date "2016-09-13T15:31:37.000+0000". We will work on this and resolve this.

In the mean time, as a workaround you may use date literals from Salesforce for increment pulls. Something like NEXT_N_DAYS:n (If it suits your requirement)

https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_dateformats.htm

**Comment by schwartzmx** [comment]
If there is anything I can help with, let me know.

Thanks

**Comment by imranece59** [comment]
@samuel-pt  Is this issue fixed? I am facing the same kind of error while doing incremental logics

**Comment by samuel-pt** [comment]
@imranece59 Not yet. Will update the ticket once it is fixed

**Comment by springml** [comment]
@schwartzmx @imranece59 

Had a look into this issue and when we specify the data as in **2016-09-13T15:31:37Z** format, data is fetched without any issues.
`val soql = "select ID,Name from Account where LastModifiedDate >= 2016-09-13T15:31:37Z"`

Please reopen this issue if you are not able to proceed.

**Comment by imranece59** [comment]
@schwartzmx  Great. It is working fine with the format which you have mentioned. Thanks
