### ISSUE TITLE
Cannot update object

### ISSUE THREAD

**Issue by franciriva** [springml/spark-salesforce#45]
Hi there,
I'm trying to update an object in salesforce with your library but the update fails with the following
`2019-10-09 09:34:15,950 ERROR [Driver] yarn.ApplicationMaster (Logging.scala:logError(91)) - User class threw exception: java.lang.NoClassDefFoundError: com/madhukaraphatak/sizeof/SizeEstimator$
java.lang.NoClassDefFoundError: com/madhukaraphatak/sizeof/SizeEstimator$
at com.springml.spark.salesforce.Utils$$anonfun$rowSize$1.apply(Utils.scala:103)
at com.springml.spark.salesforce.Utils$$anonfun$rowSize$1.apply(Utils.scala:101)
at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)...`

Here my code
`import com.amazonaws.services.glue.util.GlueArgParser  
import com.amazonaws.services.glue.util.Job  
import com.amazonaws.services.glue.util.JsonOptions  
import com.amazonaws.services.glue.{DynamicFrame, GlueContext}  
import org.apache.spark.SparkContext  
import scala.collection.JavaConverters.mapAsJavaMapConverter  
  
object SfdcUpdateData {  
  def main(sysArgs: Array[String]) {  
      
    val sparkContext: SparkContext = new SparkContext()  
    val glueContext: GlueContext = new GlueContext(sparkContext)  
    val sparkSession = glueContext.getSparkSession  
      
    val args = GlueArgParser.getResolvedOptions(sysArgs, Seq("JOB_NAME").toArray)
    Job.init(args("JOB_NAME"), glueContext, args.asJava)  
    
    val sfUrl = "https://xxx/"
    val sfInputFile = "s3://xxx/opportunity_to_update.csv"
    
    val df = sparkSession.read.format("com.databricks.spark.csv").
        option("header", "true").
        load(sfInputFile)
    
    df.write.format("com.springml.spark.salesforce").
       option("username", "xxx").
       option("password", "xxx").
       option("login", sfUrl).
       option("sfObject", "Opportunity").
       save();
       
    Job.commit()  
  }  
}`

Am I doing something wrong? Is there a missing option?
I have managed to successfully read data from Opportunity but I cannot write.

Thanks

**Comment by amin524** [comment]
Have you managed to solve this issue? I am getting the same error

**Comment by franciriva** [comment]
Nope, I eventually gave up and used Xplenty salesforce integration. Though the code would have been better. Shame

**Comment by mohankumarsivakumar** [comment]
Anyluck on fixing this issue anybody. or anyother opensource library to update salesforce data from spark

**Comment by amin524** [comment]
try to install this package before running your job :
sudo curl -L https://repo1.maven.org/maven2/com/madhukaraphatak/java-sizeof_2.11/0.1/java-sizeof_2.11-0.1.jar  -o $SPARK_JARS/java-sizeof_2.11-0.1.jar

**Comment by Hich69** [comment]
Hello,
When I wanted to execute the similar code on linux terminal, I have this issus : 
Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/services/glue/util/GlueArgParser$
	at fr.pmu.dh.transform.TransformJob$.main(TransformJob.scala:22)
	at fr.pmu.dh.transform.TransformJob.main(TransformJob.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.services.glue.util.GlueArgParser$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

I used spark-submit --class myclassname file.jar --JOB_NAME job
can someone help me please, as I don't know why it is not ok for me.
