### ISSUE TITLE
Deprecated method in Spark 2.0, being used in InferSchema

### ISSUE THREAD

**Issue by schwartzmx** [springml/spark-salesforce#5]
In Spark **2.0.0** I'm receiving this error when using `option("inferSchema","true)`.   Looks like this method was deprecated in Spark 2.0.0 https://github.com/apache/spark/pull/7605

```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.types.DecimalType$.Unlimited()Lorg/apache/spark/sql/types/DecimalType;
    at com.springml.spark.salesforce.InferSchema$.<init>(InferSchema.scala:132)
    at com.springml.spark.salesforce.InferSchema$.<clinit>(InferSchema.scala)
    at com.springml.spark.salesforce.DatasetRelation.schema(DatasetRelation.scala:181)
    at org.apache.spark.sql.execution.datasources.LogicalRelation.<init>(LogicalRelation.scala:40)
    at org.apache.spark.sql.SparkSession.baseRelationToDataFrame(SparkSession.scala:382)
    at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:143)
    at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:122)
    at org.lucidhq.SFRedshiftETL.SFObject.sfRead(SFObject.scala:205)
```

I'm having trouble building this library from source as I was going to try to fix this myself, but I'm receiving reference errors to other jars even passing the built jar on the path,  not sure if the build.sbt is out of date or something.

Just wanted to give you all a heads up.  

Cheers

**Comment by springml** [comment]
This issue is resolved by this [commit](https://github.com/springml/spark-salesforce/commit/9e1eef47b1bd5c326a60c8c1b5f316056cc892f4)
