### ISSUE TITLE
AWS EC2 Spark-Salesforce integration- java.lang.NoClassDefFoundError: com/sforce/ws/ConnectionException

### ISSUE THREAD

**Issue by dinesh1393** [springml/spark-salesforce#78]
I am getting the below error even though I generated the partner.jar correctly.

I have generated the partner.jar in my windows machine using the below jars. 
antlr-runtime-3.5.3.jar, 
force-wsc-56.1.0.jar, 
js-1.7R2.jar, 
partner.wsdl, 
ST4-4.3.4.jar, 
tools.jar,

`java -classpath tools.jar;force-wsc-56.1.0.jar;ST4-4.3.4.jar;js-1.7R2.jar;antlr-runtime-3.5.3.jar com.sforce.ws.tools.wsdlc partner.wsdl partner.jar`

I have set the class path correctly before generating the partner.jar. And I copied this partner.jar to AWS EC2 machine and try executing the below code. But its still failing with the connection error.

```
df = spark.read.format("com.springml.spark.salesforce") \ .option("username", "dinesh123@force.com") \
.option("password", "passwordtoken) \
.option("login", "https://dev-yh.develop.my.salesforce.com/")\ .option("soql", soql) \ 
 .option("inferSchema", True) \
.load()
Error:
```

**Error**
```
py4j.protocol.Py4JJavaError: An error occurred while calling o31.load.
: java.lang.NoClassDefFoundError: com/sforce/ws/ConnectionException
        at com.springml.salesforce.wave.api.APIFactory.forceAPI(APIFactory.java:49)
        at com.springml.spark.salesforce.DefaultSource.createRelation(DefaultSource.scala:102)
        at com.springml.spark.salesforce.DefaultSource.createRelation(DefaultSource.scala:50)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:350)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:274)
        at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:245)
        at scala.Option.getOrElse(Option.scala:189)
```

**Comment by Mounisha26** [comment]
Hi @dinesh1393 - Any luck in resolving the above issue?
